upload/upload.go
This appears to fix the too many open files issue when generating patients.
=> Closing the response body when done uploading

models/bundle_test.go, models/util_test.go, server/batch_controller_test.go, server/server_test.go
While `defer data.Close()` is generally _good_, it's important to call it only after you've verified that `data` was successfully opened in the first place.  Otherwise, you're trying to call a function on a nil object.
=> Fix places where a nil object might be accessed

models/parameters.go, models/util.go
This change makes sure that Parameters has the proper marshal and unmarshal
code. Also makes sure that Parameters is in MapToResource so that the
BundleEntryComponent can properly unmarshal it.
Fixes #35
=> Providing support for Parameters in Bundle entry

fixtures/search_test_data.json, search/mongo_search.go, search/mongo_search_test.go, search/search_param_types.go, search/search_param_types_test.go, search/url_query_parser.go, search/url_query_parser_test.go, server/resource_controller.go, server/server_test.go
Implement sorting on search.  Note that there are a couple of limitations:
- If a sort parameter has multiple paths, we will only consider the 1st one for sorting
- If there are multiple sort params, and some have paths containing "parallel arrays", we drop all but the first param with the "parallel paths".  This is due to a limitation in MongoDB
=> Search sort

upload/upload.go, upload/upload_test.go
Sincle UploadResources posts one at a time, its important that we post resources that are referenced BEFORE the resources that reference them (so we can fix the references to use the right IDs).  The previous algorithm was faulty.  This one probably is too, but it seems to be better.  And it is a short-term fix, as other tools should be updated to post bundles instead.
=> Fix sorting of resources in upload

models/fhirdatetime.go, models/fhirdatetime_test.go
When parsing dates, parse them into local timezone.  Why?  Because otherwise they get stored as UTC, which for our local timezone (America/New York) puts them back one day.  By storing in local timezone, we avoid that problem.  Of course, this would be a moot point if we had better handling of dates without times.
To show the problem more specifically,  if you store a date as `2012-01-02T00:00:00.0+00:00`, when you pull it out of MongoDB in the local TZ, you get `2012-01-01T19:00:00:00.0-05:00`.  For the FHIR `Date` type, this ends up changing the day from `2012-01-02` to `2012-01-01`.
=> When parsing dates, parse them into local timezone.

server.go, server/batch_controller.go, server/bind.go, server/bind_test.go, server/request_logger.go, server/resource_controller.go
When an incoming request has `Content-Type: application/json+fhir`, gin doesn't know what to do with it.  This PR adds a binding helper function that detects `application/json+fhir` and `application/xml+fhir`, delegating to the proper binding technologies.
BONUS: As part of debugging what was going on (before I realized it was an issue with `Content-Type`), I created a request logger middleware, that will log out the incoming request header and body.  You can enable it using the `--reqlog` flag.
=> Fix gin binding for application/json+fhir

search/search_param_types.go, search/search_param_types_test.go
Add support for STU3 style sorts as described in the change request:
http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=9558
For example: http://example.org/fhir/Patient?_sort=gender,-birthdate,family
Note that DSTU2-style sorts also still work. The DSTU2-style version of above is:
http://example.org/fhir/Patient?_sort=gender&_sort:desc=birthdate&_sort=family
=> STU3-style sorts

server/routing.go
If middleware was registered for "Batch", then add it to the batch handler chain.  Previously batch operations couldn't have middleware.  IE needs to setup a subscription that triggers on posted bundles, so this functionality was necessary.
=> Support Middleware for Batch Operations

search/mongo_registry.go, search/mongo_registry_test.go, search/mongo_search.go, search/mongo_search_test.go, search/registry.go, search/registry_test.go, search/search_param_types.go
New registries for registering param info, param parsers, and param bson builders (for Mongo implementation).
Currently, this is implemented just to support custom parameters, but the standard parameters should be refactored to use this system as well.
=> Custom Parameter Support

search/search_param_types.go, search/search_param_types_test.go, server/resource_controller.go
Added support for the _format parameter. Supported formats are “json”, “application/json”, and “application/json+fhir”. Unsupported formats (e.g. xml) error out.
Also fixed a small pointer bug that interferes with the content of error responses.
=> Format parameter fix

README.md, server/mongo_data_access.go, server/server_setup.go, test/interceptor.go
Interceptors now have Before(), After(), and OnError() methods that run before, after, and following a failed database operation, respectively. This was primarily motivated by the need for update interceptors to have access to resources both before AND after an update, so any changes to the resource can be detected.
=> Updated interceptor model

server/server_setup.go
Users of the server of the library have the ability to add middleware to the
FHIR resources. The way that the API works, users have access to the underlying
*gin.Engine to add any kind of middleware, but anything they do with it will
happen *before* the FHIR routes. This means that any routes registered will not
be passed through the middleware registered by the main FHIR server. This is a
huge problem when it comes to things like security. This commit lets users
register functions that will set up routes *after* the FHIR server is set up.
That allows them to be protected by security, or any other middleware, that the
FHIR server creates.
=> Work with the *gin.Engine after FHIR routes

.travis.yml, search/mongo_search.go, search/mongo_search_test.go
This PR fixes boolean search behavior and also updates the Travis config to use Go 1.7.  In addition, Travis will now test all sub-packages (without having to hard-code the names).
=> Fix boolean search + Update Travis to Go 1.7

search/mongo_search.go, search/mongo_search_test.go
All searches by id are now case sensitive and done without a regular expression. This is more performant and still meets the FHIR spec.
=> Removed case-insensitivity check from id searches

server/server_setup.go
Added middleware that responds to all requests with an Accept:application/xml or Accept:application/fhir+xml header by returning a 415 Unsupported Media Type response
=> Added middleware to reject XML requests

server/config.go, server/server_test.go
The config's ServerURL is used by auth middleware to indicate redirects.  It must be a full URL -- so the default has been changed from "localhost" to "http://localhost:3001".
=> Fix ServerURL in server.DefaultConfig

search/mongo_search_test.go, search/search_param_types.go, search/search_param_types_test.go
Chained searches with modifiers (e.g., `foo:Bar.baz`) were not properly parsed and resulted in errors.  Now they are properly parsed (e.g., param is `foo`, modifier is `Bar`, and chained query is `baz`).  Addresses #93.
=> Fix chained searches with modifiers

server/resource_controller.go
We now check the X-Forwarded-Proto header (in addition to the request's TLS settings) to determine what the original protocol of the request was before building the pagination URLs
=> Added X-Forwarded-Proto Header

server/batch_controller.go, server/config.go, server/resource_controller.go, server/routing.go
The resource and batch controllers are now passed the main server Config object. If a ServerURL is set, the controllers use the ServerURL to build the responseURLs used for pagination.
=> Controllers Use ServerURL to Generate Response URLs

server/bind.go, server/server_setup.go, server/server_test.go
STU3 changes the mime type for FHIR. The new code simply checks to see if "json"
is contained in the ContentType header.
Provided testing for the AbortNonJSONRequests function
Replaced magic number for the status with the constant from the http package.
=> Fixes confusion with JSON mime type

search/mongo_search.go, search/mongo_search_test.go
Case sensitive matching of codes, for example in the query:
`https://syntheticmass.mitre.org/fhir/Encounter?type.code=185349003` 
has a huge performance impact. Although this goes against the FHIR spec, removing the matching on codes to improve performance.
=> Removed case-insensitive matching from codes

search/mongo_search.go, search/mongo_search_test.go, search/search_param_types.go, server/mongo_data_access.go
Refactored the CreateQuery and CreatePipline methods into one Search() method that handles all mongo searches. This returns a generic results interface{} as well as a total count of the resources found on the server and any errors encountered. I refactored the tests to remove all references to CreateQuery and CreatePipeline. The decision to use a mongo pipeline for searches is now hidden from the caller, making the searcher more flexible.
=> Refactored Search

search/mongo_search.go, search/mongo_search_test.go, search/search_param_types.go, search/search_param_types_test.go
Implemented chained search using the aggregation framework. This became
complicated when handling chained ORs (see comments in mongo_search.go). Also updated unit tests.
=> Chained search

fixtures/search_test_data.json, search/mongo_search.go, search/mongo_search_test.go
Case-insensitive matching is a huge performance hit during search. Removing the case-insensitive matching in places we commonly use it to improve performance, albeit in violation of the FHIR spec.
=> Removed ci matching for strings and tokens

server/routing.go
For patient and encounter resources. As it turns out, this is still part of the FHIR 1.8 spec.
=> Restored the 'dollar-everything' endpoints

search/mongo_registry_test.go, search/mongo_search.go, search/mongo_search_test.go, server/batch_controller_test.go, server/config.go, server/mongo_data_access.go, server/mongo_indexes_test.go, server/server_setup.go, server/server_test.go
The server's `Config` object now has an `EnableCISearches` option that's passed down to the mongo searcher. When false, regexes are not used in queries against the mongo database for codes, strings, etc. Disabling the use of case-insensitivity (and regexes) improves performance for large datasets but violates the FHIR spec.
=> Made case-insensitive searching configurable

search/mongo_registry_test.go, search/mongo_search.go, search/mongo_search_test.go, server/batch_controller_test.go, server/config.go, server/middleware.go, server/middleware_test.go, server/mongo_data_access.go, server/mongo_indexes_test.go, server/server_setup.go, server/server_test.go, test/interceptor.go
This update improves and simplifies the way configuration is managed and shared when setting up a new server.  It also adds a feature to the search framework that caches the count from various searches to improve performance the next time that same search is made.
The `Config` object now has 3 new options with sensible defaults:
1. `DatabaseHost` - replaces the original database host string argument to `server.NewServer()`
2. `ReadOnly` - when true, puts the server in read-only mode and enables the `ReadOnlyMiddleware`
3. `DatabaseTimeout` - can be used to increase or decrease the timeout when making requests to mongo. This is specifically the timeout for the _database_ operation, not the web layer.
`server.NewServer()` now takes a `server.Config` object instead of just a `databaseHost` …
=> Configuration Updates

search/mongo_search.go, search/mongo_search_test.go
The 'total' field was being overwritten with 0 by an m.aggregate() or m.find() operation, even if doCount was false. I renamed the field collected from m.aggregate() and m.find() to 'computedTotal', and total=computedTotal unless doCount = false.
=> Fixed count cache mechanism

search/mongo_search.go, search/mongo_search_test.go
Searches with 0 results were returning nil instead of an empty slice of resources. Fixed this to return the empty slice appropriate for the searched resource type.
=> Fixed search results bug

search/mongo_search.go, search/mongo_search_test.go
The resource type was not incorporated into the hash of the query, so requests for different resource types would return the same hash, for example:
`GET [base]/Patient` and `GET [base]/Observation` were both hashing just the query portion of the request, or `""`. Now, requests to these endpoints hash `Patient?` and `Observation?` respectively, ensuring there is no conflict.
=> Fixed conficting hashes when caching resource counts

search/mongo_registry_test.go, search/mongo_search.go, search/mongo_search_test.go, server/config.go, server/mongo_data_access.go
The CountTotalResults config option may now be set to false to prevent the server from making a count of the total results of a search. This improves performance on large datasets.
=> Disable Search Counts

search/mongo_search.go, server/mongo_data_access.go, server/server_test.go
Fixed paging links to work without a result count. Without a total count we are unable to generate the 'last' link, but we can still reliably return a 'next' link. This still conforms to spec.
=> Paging Links Without Counts

search/mongo_search.go, server/config.go, server/data_access.go, server/mongo_admin.go, server/mongo_indexes.go, server/mongo_indexes_test.go, server/server_setup.go
Added a background thread to the server to periodically scan for long-running client-initiated operations, killing any operations that exceed Config.DatabaseOpTimeout. This thread is started _after_ ensuring all indexes, so no `ensureIndex()` processes are accidentally killed.
The following is the general idea:
* The `admin` database is queried for long-running ops once every 10 seconds.
* Long-running ops are killed if they've consumed more than 90 seconds of processing time and haven't yet completed.
* The socket connection to the database is killed after 2 minutes, in case the client operation hangs for some other reason.
I've tested this feature manually and things are working well. I'm not sure how to write a unit test for this though, since I can't think of a way to force the …
=> Added KillLongRunningOps

search/mongo_search.go, search/mongo_search_test.go, search/search_param_types.go, search/search_param_types_test.go, server/mongo_data_access.go, server/server_test.go
Added the `_summary=count` search option, and refined the way paging links are built. Queries that don't support paging (e.g. `$everything`, or `_summary=count`) only return a self link now (built from the raw query, without the _offset or _count params included). 
Also, `_summary=count` will return a total even if `Config.CountTotalResults = false`. Otherwise this search would be completely useless in that scenario.
=> Implemented _summary=count
